--- #YAML:1.0
name:               Device-Delcom-VSI
version:            0.08
abstract:           Use Device::USB to access Delcom VSI devices.
author:
    - G. Wade Johnson <wade@anomaly.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Device::USB:  0
    Test::More:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
